### ISSUE TITLE
What's the license actually used?

### ISSUE THREAD

**Issue by predator2k** [ZipCPU/eth10g#3]
Great work. But I wonder which license do you choose for this project? I see you choose Apache 2.0 in https://zipcpu.com/blog/2023/11/25/eth10g.html but github now shows it's GPLv3. 

Could you please clarify this? Thank you for your reply.

**Comment by ZipCPU** [comment]
Absolutely, and my apologies for any confusion.  The license was driven by the project sponsors.  Initially it was required to be Apache 2.0, and then I was directed to make it GPLv3.  So the project is currently available under GPLv3.

Feel free to write me if you have other needs, and we can discuss them.

**Comment by predator2k** [comment]
Ok
